package:
    name: carchivetools
    version: 1.9.0

source:
    git_url: https://github.com/NSLS-II/carchivetools
    git_rev: conda-1.9

build:
    number: 3

requirements:
    build:
        - python
        - setuptools
        - numpy
        - protobuf
    run:
        - python
        - numpy
        - twisted
        - protobuf

test:
    imports:
        - carchive

about:
    home: https://github.com/epicsdeb/carchivetools
    summary: Channel Archiver shell tools and library
