package:
    name: carchivetools
    version: 2.0.0

source:
    git_url: https://github.com/NSLS-II/carchivetools
    git_rev: conda-2.0

build:
    number: 2

requirements:
    build:
        - python
        - setuptools
        - numpy
        - protobuf
    run:
        - python
        - numpy
        - twisted
        - protobuf

test:
    imports:
        - carchive

about:
    home: https://github.com/epicsdeb/carchivetools
    summary: Channel Archiver shell tools and library
